In [1]:
import polars as pl
from getpass import getpass
from sqlalchemy import create_engine, URL

from tqdm import tqdm

In [2]:
username = input("Username:")
password = getpass("Password:")

Username: iedb_svc
Password: ········

In [3]:
iedb_url = URL.create(
    "mysql+mysqlconnector",
    username=username,
    password=password,  # plain (unescaped) text
    host="81.177.141.179",
    port = 3306,
    database="IEDB"
)
cedar_url = URL.create(
    "mysql+mysqlconnector",
    username=username,
    password=password,  # plain (unescaped) text
    host="81.177.141.179",
    port = 3306,
    database="CEDAR"
)

In [10]:
iedb_uri = f"mysql://{username}:{password}@81.177.141.179:3306/IEDB"
cedar_uri = f"mysql://{username}:{password}@81.177.141.179:3306/CEDAR"
tables["organism_names"] = pl.read_database_uri(query = "SELECT organism_id, name_txt FROM organism_names WHERE name_class = 'scientific name';", uri = iedb_uri)
tables["organism_names"].head()

shape: (5, 2)
┌─────────────┬─────────────────────────┐
│ organism_id ┆ name_txt                │
│ ---         ┆ ---                     │
│ f64         ┆ str                     │
╞═════════════╪═════════════════════════╡
│ 1.0         ┆ root                    │
│ 2.0         ┆ Bacteria                │
│ 106.0       ┆ Runella slithyformis    │
│ 108.0       ┆ Spirosoma linguale      │
│ 139.0       ┆ Borreliella burgdorferi │
└─────────────┴─────────────────────────┘

In [ ]:
table_names = ["tcell","curated_epitope","object","epitope_object","epitope", "tcell_receptor","curated_receptor","distinct_receptor","distinct_chain","mhc_allele_restriction"]
tables = {}
conn = create_engine(iedb_url)
batch_size = 100000
for name in tqdm(table_names):
    tbl = pl.DataFrame()
    for chunk in tqdm(pl.read_database(query = f"SELECT * FROM {name};", connection=conn.connect(), batch_size = batch_size, iter_batches=True,infer_schema_length=10000)):
        tbl = pd.concat([tbl, chunk])
    tables[name] = tbl

In [ ]:
tcell_iter = pl.read_database(query = f"SELECT * FROM {name};", connection=conn.connect(), batch_size = batch_size, iter_batches=True,infer_schema_length=10000)

In [5]:
%%time
from mysql.connector import connect, Error as MysqlError
import pandas as pd
chunk_size = 100000
conn = create_engine(iedb_url)
tbl = pd.DataFrame()
for chunk in tqdm(pd.read_sql(f"SELECT * FROM tcell;", con = conn.connect(), chunksize = chunk_size)):
    tbl = pd.concat([tbl, chunk], ignore_index = False)
tbl.head()

6it [00:12,  2.04s/it]

CPU times: user 32.2 s, sys: 2.51 s, total: 34.7 s
Wall time: 5min 50s

,tcell_id,reference_id,curated_epitope_id,as_location,as_type_id,as_char_value,as_num_value,as_inequality,as_num_subjects,as_num_responded,...,apc_h_sex,apc_h_mhc_types_present,ant_type,ant_ref_name,ant_object_id,ant_ev,ant_con_object_id,complex_id,tcr_object_id,adt_tcr_object_id
0,3563412.0,1012909.0,1306899.0,Figure 8,583.0,Positive,0.11,NaN,NaN,NaN,...,NaN,NaN,Epitope,Tax 11-19,702738.0,Exact match to reference information,NaN,NaN,3007369.0,None
1,3563413.0,1012909.0,1306899.0,Figure 8,582.0,Positive,45800.00,NaN,NaN,NaN,...,NaN,NaN,Epitope,Tax 11-19,702738.0,Exact match to reference information,NaN,NaN,3007371.0,None
2,3563414.0,1012909.0,1213130.0,Figure 8,583.0,Positive,0.11,NaN,NaN,NaN,...,NaN,NaN,Epitope,Tax-5K-IBA,454601.0,Exact match to reference information,NaN,NaN,3007374.0,None
3,3620516.0,1012909.0,1213130.0,Figure 8,582.0,Positive-Low,560.00,NaN,NaN,NaN,...,NaN,NaN,Epitope,Tax-5K-IBA,454601.0,Exact match to reference information,NaN,NaN,3056631.0,None
4,3183.0,478.0,1153.0,Figure 4,67.0,Positive,NaN,NaN,1.0,1.0,...,NaN,NaN,Epitope,SYT-SSX B peptide,11324.0,Exact match to reference information,NaN,NaN,NaN,None